name: registrovot
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'


dependencies:
  firebase_core: ^2.6.0
  firebase_auth: ^4.2.7
  shared_preferences: ^2.0.17  
  get: ^4.6.5
  awesome_dialog: ^3.0.2
  loading_animation_widget: ^1.2.0+4
  dropdown_button2: ^1.9.4
  cloud_firestore: ^4.4.3
  equatable: ^2.0.5
  syncfusion_flutter_calendar: ^21.2.3
  flutter_map: ^4.0.0
  latlong2: ^0.8.0
  intl: ^0.18.0
  flutter_localization: ^0.1.11

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:

  - assets/
  - assets/images/
  fonts:
    - family: AvantGardeStd
      fonts:
        - asset: assets/font/ITCAvantGardeStd-Md.otf
        - asset: assets/font/ITCAvantGardeStd-Bold.otf




